# Generated by Django 4.2 on 2023-04-23 09:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('loveRelay', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='receiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to=settings.AUTH_USER_MODEL, verbose_name='接收者'),
        ),
        migrations.AddField(
            model_name='message',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL, verbose_name='发送者'),
        ),
        migrations.AddField(
            model_name='giftrecord',
            name='gift',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loveRelay.gift', verbose_name='礼物'),
        ),
        migrations.AddField(
            model_name='giftrecord',
            name='message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loveRelay.message', verbose_name='留言'),
        ),
        migrations.AddField(
            model_name='giftrecord',
            name='receiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_gifts', to=settings.AUTH_USER_MODEL, verbose_name='接收者'),
        ),
        migrations.AddField(
            model_name='giftrecord',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_gifts', to=settings.AUTH_USER_MODEL, verbose_name='发送者'),
        ),
    ]
