# Generated by Django 4.2 on 2023-05-03 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_profile_record_remove_question_option1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='date',
            field=models.DateField(auto_now=True, verbose_name='日期'),
        ),
    ]
